{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microapigw.serviceAccountName" . }}
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "microapigw.labels" . | nindent 4 }}
{{- if .Values.image.imagePullSecretName }}
imagePullSecrets:
- name: {{ .Values.image.imagePullSecretName }}
{{- end }}
{{- end }}

