apiVersion: v1
kind: Service
metadata:
  name: {{ include "microapigw.fullname" . }}
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "microapigw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "microapigw.selectorLabels" . | nindent 4 }}


